version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - ${PORT}
    environment:
      WORDPRESS_DB_HOST: ${MYSQLHOST}:${MYSQLPORT}
      WORDPRESS_DB_USER: ${MYSQLUSER}
      WORDPRESS_DB_PASSWORD: ${MYSQLPASSWORD}
      WORDPRESS_DB_NAME: ${MYSQLDATABASE}
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword